version: 1.0.0.{build}

image: Visual Studio 2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - git clone https://github.com/ivmai/bdwgc.git
  - cmake -G "NMake Makefiles" .
  - cmake --build . --config Release
