version: 1.0.0.{build}

image: Visual Studio 2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - curl -O "https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz"
  - tar xf gc-8.0.4.tar.gz
  - mv gc-8.0.4 bdwgc
  - cmake -G "NMake Makefiles" .
  - cmake --build . --config Release
