# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/joy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/joy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/joy/CMakeFiles /cygdrive/c/joy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/joy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named joy

# Build rule for target.
joy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joy
.PHONY : joy

# fast build rule for target.
joy/fast:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/build
.PHONY : joy/fast

interp.o: interp.c.o

.PHONY : interp.o

# target to build an object file
interp.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/interp.c.o
.PHONY : interp.c.o

interp.i: interp.c.i

.PHONY : interp.i

# target to preprocess a source file
interp.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/interp.c.i
.PHONY : interp.c.i

interp.s: interp.c.s

.PHONY : interp.s

# target to generate assembly for a file
interp.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/interp.c.s
.PHONY : interp.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.s
.PHONY : main.c.s

scan.o: scan.c.o

.PHONY : scan.o

# target to build an object file
scan.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/scan.c.o
.PHONY : scan.c.o

scan.i: scan.c.i

.PHONY : scan.i

# target to preprocess a source file
scan.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/scan.c.i
.PHONY : scan.c.i

scan.s: scan.c.s

.PHONY : scan.s

# target to generate assembly for a file
scan.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/scan.c.s
.PHONY : scan.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... joy"
	@echo "... interp.o"
	@echo "... interp.i"
	@echo "... interp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... scan.o"
	@echo "... scan.i"
	@echo "... scan.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

